name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  release:
    types: [ published ]

env:
  DOCKERHUB_PREFIX: docker.io
  GITHUB_CONTAINER_PREFIX: ghcr.io
  DOCKER_IMAGE: wiki

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_PREFIX }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_CONTAINER_PREFIX }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: |
            - linux/amd64
            - linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta by docs https://github.com/docker/metadata-action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_PREFIX }}/dselen/${{ env.DOCKER_IMAGE }}
            ${{ env.GITHUB_CONTAINER_PREFIX }}/daanselen/${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and export (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

#  docker_scan:
#    if: ${{ github.event_name != 'pull_request' }}
#    runs-on: ubuntu-latest
#    needs: docker_build
#    steps:
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.DOCKERHUB_PREFIX }}
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Docker Scout CVEs
#        uses: docker/scout-action@v1
#        with:
#          command: cves
#          image: ${{ env.GITHUB_CONTAINER_PREFIX }}/${{ env.DOCKER_IMAGE }}:main
#          only-severities: critical,high
#          only-fixed: true
#          write-comment: true
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          exit-code: true
#
#      - name: Docker Scout Compare
#        uses: docker/scout-action@v1
#        with:
#          command: compare
#          # Set to Github for maximum compat
#          image: ${{ env.GITHUB_CONTAINER_PREFIX }}/${{ env.DOCKER_IMAGE }}:main
#          to: ${{ env.GITHUB_CONTAINER_PREFIX }}/${{ env.DOCKER_IMAGE }}:latest
#          only-severities: critical,high
#          ignore-unchanged: true
#          github-token: ${{ secrets.GITHUB_TOKEN }}
